apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: "mysql"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: mutthu2512/mysql:{{ .Values.deployment.imageVersion }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
           name: backend
        

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port