apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels: # these labels are deployment labels
    app: backend
    project: expense
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: # these labels are used to find the pods
      app: backend
      project: expense
      tier: app
  template:
    metadata:
      labels: # these labels are pod labels
        app: backend
        project: expense
        tier: app
    spec:
      containers:
      - name: backend
        image: mutthu2512/backend:{{ .Values.deployment.imageVersion }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port